name: Generate ascii 
on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: execute shell
              run: |
                chmod 755 ascii-script.sh
                ./ascii-script.sh  
            # - name: install cowsay program
            #   run: sudo apt-get install cowsay -y

            # - name: execute cowsay cmd
            #   run: cowsay -f dragon "Run for cover, I am a Dragon...RAWR" >> dragon.txt   
            # - name: test file existes
            #   run: grep -i "dragon" dragon.txt
            # - name: read file
            #   run: cat dragon.txt
            # - name: Checkout repo files
            #   run: ls -lrta      