name: Build muliple jobs
on: push

jobs:
    build_job1:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
    
        - name: install cowsay program
          run: sudo apt-get install cowsay -y
            
        - name: execute cowsay cmd
          run: cowsay -f dragon "Run for cover, I am a Dragon...RAWR" >> dragon.txt  
        - name: upload dragon text file
          uses: actions/upload-artifact@v4
          with:
            name: myartifact
            path: dragon.txt 

    test_job2:
        runs-on: ubuntu-latest
        needs: build_job1
        steps:
        - name: sleep for 30 sec
          run: sleep 30
        - name: test file existes
          run: grep -i "dragon" dragon.txt  

        - uses: actions/download-artifact@v4
          with:
            name: my-artifact
            


        
    deploy_job3: 
        runs-on: ubuntu-latest
        needs: test_job2
        steps:
        - name: read file
          run: cat dragon.txt
        - name: list repo files
          run: ls -lrta   
        - uses: actions/download-artifact@v4
          with:
            name: my-artifact       
