name: my first workflow
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: my first action
              run: |
                echo "testing my first action"
                ls -lrta
                cat README.md
           
                shell: bash
            - name: GEnerate ASCII 
              run: cowsay -f dragon "Run for cover, I am a Dragon...RAWR" >> dragon.txt   